const state={stats:null,editions:[],norms:[],procurements:[],intelligence:null,sync:null};
const $=id=>document.getElementById(id);
const fmt=new Intl.NumberFormat('es-AR');
const PAGE_SIZE=25;
const dtf=new Intl.DateTimeFormat('es-AR',{timeZone:'America/Argentina/Buenos_Aires',dateStyle:'short',timeStyle:'medium'});
async function fetchJson(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`${path}: HTTP ${r.status}`);return r.json()}
async function fetchOptional(path){try{return await fetchJson(path)}catch(e){console.warn(`optional dataset unavailable: ${path}`,e);return null}}
async function loadData(){const [stats,editions,norms,procurements,intelligence,sync]=await Promise.all([fetchJson('data/stats.json'),fetchJson('data/editions.json'),fetchJson('data/norms.json'),fetchJson('data/procurements.json'),fetchOptional('data/procurement_intelligence.json'),fetchOptional('data/sync_manifest.json')]);Object.assign(state,{stats,editions,norms,procurements,intelligence,sync});$('data-status').textContent='Datos conectados';$('data-status').className='status status-ok'}
function fillSelect(el,values){for(const v of values){const o=document.createElement('option');o.value=v;o.textContent=v;el.appendChild(o)}}
function populateFilters(){fillSelect($('filter-org'),[...new Set(state.norms.map(x=>x.organismo).filter(Boolean))].sort());fillSelect($('filter-type'),[...new Set(state.norms.map(x=>x.tipo).filter(Boolean))].sort());fillSelect($('filter-category'),[...new Set(state.procurements.map(x=>x.categoria).filter(Boolean))].sort())}
function filteredNorms(){const q=$('filter-search').value.trim().toLowerCase(),org=$('filter-org').value,type=$('filter-type').value;return state.norms.filter(n=>{const hay=`${n.nombre||''} ${n.sumario||''} ${n.organismo||''} ${n.tipo||''}`.toLowerCase();return(!q||hay.includes(q))&&(!org||n.organismo===org)&&(!type||n.tipo===type)})}
function filteredProcurements(){const q=$('filter-search').value.trim().toLowerCase(),org=$('filter-org').value,type=$('filter-type').value,cat=$('filter-category').value;return state.procurements.filter(n=>{const hay=`${n.nombre||''} ${n.sumario||''} ${n.organismo||''} ${n.tipo||''} ${n.categoria||''}`.toLowerCase();return(!q||hay.includes(q))&&(!org||n.organismo===org)&&(!type||n.tipo===type)&&(!cat||n.categoria===cat)})}
function uniqueProcessCount(rows){return new Set(rows.map(x=>x.proceso_id||x.id_norma)).size}
function renderMetrics(){const latest=[...state.editions].sort((a,b)=>Number(b.numero_boletin)-Number(a.numero_boletin))[0];$('metric-bulletin').textContent=latest?`N.º ${latest.numero_boletin}`:'—';$('metric-bulletin-date').textContent=latest?.fecha_publicacion||'—';$('metric-norms').textContent=fmt.format(state.stats?.norms??state.norms.length);$('metric-procurements').textContent=fmt.format(state.stats?.procurements??uniqueProcessCount(state.procurements));$('metric-editions').textContent=fmt.format(state.stats?.editions??state.editions.length);$('data-generated-at').textContent=state.stats?.generated_at?`Datos generados ${dtf.format(new Date(state.stats.generated_at))} ART`:'histórico disponible';const syncAt=state.sync?.public_synced_at||state.sync?.published_at;$('dashboard-sync-at').textContent=syncAt?`Dashboard sincronizado ${dtf.format(new Date(syncAt))} ART`:'Dashboard sin sincronización automática registrada'}
function renderIntelligence(){const s=state.intelligence?.summary;if(!s){$('intel-status').textContent='sin sincronizar';$('metric-tech').textContent='—';$('metric-cyber').textContent='—';$('intel-tags').innerHTML='<div class="empty">La capa Intelligence todavía no fue publicada en el repositorio público.</div>';return}$('intel-status').textContent='activo';$('metric-tech').textContent=fmt.format(s.technology_related||0);$('metric-cyber').textContent=fmt.format(s.cybersecurity_related||0);const rows=Object.entries(s.tag_counts||{}).sort((a,b)=>b[1]-a[1]),max=rows[0]?.[1]||1;$('intel-tags').innerHTML=rows.length?rows.map(([k,v])=>`<div class="bar-row"><div class="bar-label">${esc(k.replaceAll('_',' '))}</div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(4,v/max*100)}%"></div></div><div class="bar-value">${v}</div></div>`).join(''):'<div class="empty">Sin etiquetas tecnológicas.</div>';renderVendors(s.vendor_mentions||{})}
function renderVendors(vendors){const rows=Object.entries(vendors).sort((a,b)=>b[1]-a[1]).slice(0,8);$('vendor-ranking').innerHTML=rows.map(([name,value],i)=>`<div class="rank-row"><span class="rank-index">${i+1}</span><span class="rank-name">${esc(name)}</span><span class="rank-value">${value}</span></div>`).join('')||''}
function renderBAC(){const section=$('bac-status')?.closest('.panel')||$('bac-status')?.parentElement;if(section)section.style.display='none'}
function renderSyncNotice(){const missing=[];if(!state.intelligence)missing.push('Intelligence');if(!state.sync)missing.push('registro de sincronización');if(missing.length){$('sync-notice').innerHTML=`<strong>Dashboard v1 mejorada.</strong> Datos base operativos. Pendiente de sincronización pública: ${esc(missing.join(' + '))}.`}else{const bulletin=state.sync.latest_bulletin?` Boletín N.º ${esc(state.sync.latest_bulletin)} sincronizado.`:'';$('sync-notice').innerHTML=`<strong>Dashboard v1 mejorada.</strong> Boletín e Intelligence sincronizados.${bulletin}`}}
function renderBars(){const rowsSource=filteredProcurements();const seen=new Set(),uniqueRows=[];for(const x of rowsSource){const pid=x.proceso_id||x.id_norma;if(seen.has(pid))continue;seen.add(pid);uniqueRows.push(x)}const counts={};for(const x of uniqueRows)counts[x.categoria||'otros']=(counts[x.categoria||'otros']||0)+1;const rows=Object.entries(counts).sort((a,b)=>b[1]-a[1]),max=rows[0]?.[1]||1;$('procurement-total').textContent=fmt.format(uniqueRows.length);$('category-bars').innerHTML=rows.length?rows.map(([k,v])=>`<div class="bar-row"><div class="bar-label">${esc(k.replaceAll('_',' '))}</div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(4,v/max*100)}%"></div></div><div class="bar-value">${v}</div></div>`).join(''):'<div class="empty">Sin resultados.</div>'}
function renderOrgRanking(){const counts={};for(const x of filteredNorms()){const k=x.organismo||'Sin organismo';counts[k]=(counts[k]||0)+1}const rows=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,8);$('org-ranking').innerHTML=rows.map(([name,value],i)=>`<div class="rank-row"><span class="rank-index">${i+1}</span><span class="rank-name">${esc(name)}</span><span class="rank-value">${value}</span></div>`).join('')||'<div class="empty">Sin resultados.</div>'}
function recordHtml(n,proc){const pills=[n.organismo,n.tipo,`Boletín ${n.numero_boletin}`].filter(Boolean).map(v=>`<span class="meta-pill">${esc(String(v))}</span>`);if(proc&&n.categoria)pills.unshift(`<span class="meta-pill category">${esc(n.categoria.replaceAll('_',' '))}</span>`);const link=n.url_norma?`<a class="record-action" href="${attr(n.url_norma)}" target="_blank" rel="noopener">Documento oficial ↗</a>`:'';return `<article class="record"><div><h3 class="record-title">${esc(n.nombre||`Norma ${n.id_norma}`)}</h3><div class="record-meta">${pills.join('')}</div><p class="record-summary">${esc(n.sumario||'Sin sumario disponible.')}</p></div>${link}</article>`}
function renderLists(){const nr=filteredNorms(),pr=filteredProcurements(),nshow=nr.slice(0,PAGE_SIZE),pshow=pr.slice(0,PAGE_SIZE);$('norm-result-count').textContent=fmt.format(nr.length);$('proc-result-count').textContent=fmt.format(pr.length);$('norm-list').innerHTML=nshow.map(n=>recordHtml(n,false)).join('')||'<div class="empty">Sin normas.</div>';$('procurement-list').innerHTML=pshow.map(n=>recordHtml(n,true)).join('')||'<div class="empty">Sin contrataciones.</div>'}
function renderAll(){renderMetrics();renderIntelligence();renderBAC();renderSyncNotice();renderBars();renderOrgRanking();renderLists()}
function bind(){['filter-search','filter-org','filter-type','filter-category'].forEach(id=>$(id).addEventListener(id==='filter-search'?'input':'change',renderAll));$('clear-filters').addEventListener('click',()=>{$('filter-search').value='';$('filter-org').value='';$('filter-type').value='';$('filter-category').value='';renderAll()})}
function esc(v=''){return String(v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function attr(v=''){return esc(v).replace(/'/g,'&#39;')}
(async()=>{try{await loadData();populateFilters();bind();renderAll()}catch(e){console.error(e);$('data-status').textContent='Datos no disponibles';$('data-status').className='status status-error';$('dashboard-sync-at').textContent=e.message}})();