const state={stats:null,editions:[],norms:[],procurements:[]};
const $=id=>document.getElementById(id);
const fmt=new Intl.NumberFormat('es-AR');
const PAGE_SIZE=25;
async function fetchJson(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`${path}: HTTP ${r.status}`);return r.json()}
async function loadData(){const d={stats:await fetchJson('data/stats.json'),editions:await fetchJson('data/editions.json'),norms:await fetchJson('data/norms.json'),procurements:await fetchJson('data/procurements.json')};Object.assign(state,d);$('data-status').textContent='Datos conectados';$('data-status').className='status status-ok'}
function fillSelect(el,values){for(const v of values){const o=document.createElement('option');o.value=v;o.textContent=v;el.appendChild(o)}}
function populateFilters(){fillSelect($('filter-org'),[...new Set(state.norms.map(x=>x.organismo).filter(Boolean))].sort());fillSelect($('filter-type'),[...new Set(state.norms.map(x=>x.tipo).filter(Boolean))].sort());fillSelect($('filter-category'),[...new Set(state.procurements.map(x=>x.categoria).filter(Boolean))].sort())}
function filteredNorms(){const q=$('filter-search').value.trim().toLowerCase(),org=$('filter-org').value,type=$('filter-type').value;return state.norms.filter(n=>{const hay=`${n.nombre||''} ${n.sumario||''} ${n.organismo||''} ${n.tipo||''}`.toLowerCase();return(!q||hay.includes(q))&&(!org||n.organismo===org)&&(!type||n.tipo===type)})}
function filteredProcurements(){const q=$('filter-search').value.trim().toLowerCase(),org=$('filter-org').value,type=$('filter-type').value,cat=$('filter-category').value;return state.procurements.filter(n=>{const hay=`${n.nombre||''} ${n.sumario||''} ${n.organismo||''} ${n.tipo||''} ${n.categoria||''}`.toLowerCase();return(!q||hay.includes(q))&&(!org||n.organismo===org)&&(!type||n.tipo===type)&&(!cat||n.categoria===cat)})}
function renderMetrics(){const latest=[...state.editions].sort((a,b)=>Number(b.numero_boletin)-Number(a.numero_boletin))[0];$('metric-bulletin').textContent=latest?`N.º ${latest.numero_boletin}`:'—';$('metric-bulletin-date').textContent=latest?.fecha_publicacion||'—';$('metric-norms').textContent=fmt.format(state.stats?.norms??state.norms.length);$('metric-procurements').textContent=fmt.format(state.stats?.procurements??state.procurements.length);$('metric-editions').textContent=fmt.format(state.stats?.editions??state.editions.length);if(state.stats?.generated_at){const d=new Date(state.stats.generated_at);$('updated-at').textContent=`Actualizado ${new Intl.DateTimeFormat('es-AR',{timeZone:'America/Argentina/Buenos_Aires',dateStyle:'short',timeStyle:'medium'}).format(d)} ART`}}
function renderBars(){const rowsSource=filteredProcurements(),counts={};for(const x of rowsSource)counts[x.categoria||'otros']=(counts[x.categoria||'otros']||0)+1;const rows=Object.entries(counts).sort((a,b)=>b[1]-a[1]),max=rows[0]?.[1]||1;$('procurement-total').textContent=fmt.format(rowsSource.length);$('category-bars').innerHTML=rows.length?rows.map(([k,v])=>`<div class="bar-row"><div class="bar-label">${esc(k.replaceAll('_',' '))}</div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(4,v/max*100)}%"></div></div><div class="bar-value">${v}</div></div>`).join(''):'<div class="empty">Sin resultados.</div>'}
function renderOrgRanking(){const counts={};for(const x of filteredNorms()){const k=x.organismo||'Sin organismo';counts[k]=(counts[k]||0)+1}const rows=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,8);$('org-ranking').innerHTML=rows.map(([name,value],i)=>`<div class="rank-row"><span class="rank-index">${i+1}</span><span class="rank-name">${esc(name)}</span><span class="rank-value">${value}</span></div>`).join('')||'<div class="empty">Sin resultados.</div>'}
function recordHtml(n,proc){const pills=[n.organismo,n.tipo,`Boletín ${n.numero_boletin}`].filter(Boolean).map(v=>`<span class="meta-pill">${esc(String(v))}</span>`);if(proc&&n.categoria)pills.unshift(`<span class="meta-pill category">${esc(n.categoria.replaceAll('_',' '))}</span>`);const link=n.url_norma?`<a class="record-action" href="${attr(n.url_norma)}" target="_blank" rel="noopener">Documento oficial ↗</a>`:'';return `<article class="record"><div><h3 class="record-title">${esc(n.nombre||`Norma ${n.id_norma}`)}</h3><div class="record-meta">${pills.join('')}</div><p class="record-summary">${esc(n.sumario||'Sin sumario disponible.')}</p></div>${link}</article>`}
function renderLists(){const nr=filteredNorms(),pr=filteredProcurements(),nshow=nr.slice(0,PAGE_SIZE),pshow=pr.slice(0,PAGE_SIZE);$('norm-result-count').textContent=fmt.format(nr.length);$('proc-result-count').textContent=fmt.format(pr.length);$('norm-list').innerHTML=nshow.map(n=>recordHtml(n,false)).join('')||'<div class="empty">Sin normas.</div>';$('procurement-list').innerHTML=pshow.map(n=>recordHtml(n,true)).join('')||'<div class="empty">Sin contrataciones.</div>'}
function renderAll(){renderMetrics();renderBars();renderOrgRanking();renderLists()}
function bind(){['filter-search','filter-org','filter-type','filter-category'].forEach(id=>$(id).addEventListener(id==='filter-search'?'input':'change',renderAll));$('clear-filters').addEventListener('click',()=>{$('filter-search').value='';$('filter-org').value='';$('filter-type').value='';$('filter-category').value='';renderAll()})}
function esc(v=''){return String(v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function attr(v=''){return esc(v).replace(/'/g,'&#39;')}
(async()=>{try{await loadData();populateFilters();bind();renderAll()}catch(e){console.error(e);$('data-status').textContent='Datos no disponibles';$('data-status').className='status status-error';$('updated-at').textContent=e.message}})();